[build]
  command = "npm run build"
  publish = "dist"

[template.environment]
  VUE_APP_API_KEY = "AIzaSyBOe52r6ADAinscrFbn5WJhyLAPEXCVF1w"
  VUE_APP_FIREBASE_API_KEY = "AIzaSyAfMqUUoqHZTXG4aeseJ8R2UGVomDR4c7Q"
  VUE_APP_FIREBASE_AUTH_DOMAIN = "geomeoww-nekos.firebaseapp.com"
  VUE_APP_FIREBASE_DATABASE_URL = "https://geomeoww-nekos-default-rtdb.europe-west1.firebasedatabase.app"
  VUE_APP_FIREBASE_PROJECT_ID = "geomeoww-neko"
  VUE_APP_STORAGE_BUCKET = "geomeoww-nekos.appspot.com"
  VUE_APP_FIREBASE_MESSAGING_SENDER_ID = "950561557687"
  VUE_APP_FIREBASE_APP_ID = "1:950561557687:web:ba3753bf04b028eed0d132"
  VUE_APP_FIREBASE_MEASUREMENT_ID = "G-RLH3HGYSE1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
